/*------------------------------------------------------------------------------
MASV: 1412503
HỌ TÊN: NGUYỄN THỊ THANH THẢO
LAB: 03
NGÀY: 31/5/2017
--------------------------------------------------------------------------------*/
--create database QLSV

use QLSV

/*------------------------------------------------------------------------------
MASV: 1412503
HỌ TÊN: NGUYỄN THỊ THANH THẢO
LAB: 03
NGÀY: 31/5/2017
--------------------------------------------------------------------------------*/
CREATE TABLE SINHVIEN(
	MASV NVARCHAR(20) PRIMARY KEY,
	HOTEN NVARCHAR(100) NOT NULL,
	NGAYSINH DATETIME,
	DIACHI NVARCHAR(200),
	MALOP VARCHAR(20),
	TENDN NVARCHAR(100) NOT NULL, 
	MATKHAU VARBINARY(1000) NOT NULL
)

CREATE TABLE NHANVIEN(
	MANV VARCHAR (20) PRIMARY KEY,
	HOTEN NVARCHAR(100) NOT NULL,
	EMAIL VARCHAR(20),
	LUONG VARBINARY(1000),
	TENDN NVARCHAR(100) NOT NULL,
	MATKHAU VARBINARY(1000) NOT NULL
)

CREATE TABLE LOP(
	MALOP VARCHAR(20) PRIMARY KEY,
	TENLOP NVARCHAR(100) NOT NULL,
	MANV VARCHAR(20)
)

ALTER TABLE SINHVIEN
ADD CONSTRAINT FK_SINHVIEN_LOP
FOREIGN KEY (MALOP)
REFERENCES LOP(MALOP)

ALTER TABLE LOP
ADD CONSTRAINT FK_LOP_NHANVIEN
FOREIGN KEY (MANV)
REFERENCES NHANVIEN(MANV)

GO
CREATE PROC SP_INS_SINHVIEN @MASV NVARCHAR(20), @HOTEN NVARCHAR(100), @NGAYSINH DATETIME, @DIACHI NVARCHAR(200), @MALOP VARCHAR(20), @TENDN NVARCHAR(100), @MATKHAU VARCHAR(100)
AS
BEGIN
	INSERT INTO SINHVIEN VALUES (@MASV, @HOTEN, @NGAYSINH, @DIACHI, @MALOP, @TENDN, HASHBYTES('MD5', CONVERT( VARBINARY, @MATKHAU)))
END

--INSERT INTO LOP VALUES ('14CTT3', N'Công nghệ thông tin', null)
--EXEC SP_INS_SINHVIEN '1412123', N'Nguyễn Hoài Anh', '1996/10/9', N'TP Hồ Chí Minh', '14CTT3', '1412123', 'hoaianh123'
--select * from SINHVIEN where TENDN = '1412123'

GO
CREATE CERTIFICATE LUONG   
  ENCRYPTION BY PASSWORD = '1412503'  
  WITH SUBJECT = 'LUONG'

GO
CREATE SYMMETRIC KEY SSN_Key_LUONG 
    WITH ALGORITHM = AES_256,
	KEY_SOURCE = '1412503'  
	ENCRYPTION BY CERTIFICATE LUONG;

GO
CREATE PROC SP_INS_NHANVIEN @MANV VARCHAR(20), @HOTEN NVARCHAR(100), @EMAIL  VARCHAR(20), @LUONG INT, @TENDN NVARCHAR(100), @MATKHAU VARCHAR(100)
AS
BEGIN
	OPEN SYMMETRIC KEY SSN_Key_LUONG DECRYPTION BY CERTIFICATE LUONG WITH PASSWORD = '1412503';
	INSERT INTO NHANVIEN VALUES (@MANV, @HOTEN, @EMAIL, EncryptByKey(Key_GUID('SSN_Key_LUONG'), CONVERT( VARBINARY, @LUONG)), @TENDN, HASHBYTES('SHA1', CONVERT( VARBINARY, @MATKHAU)))
END

GO
CREATE PROC SP_SEL_NHANVIEN 
AS
BEGIN
	OPEN SYMMETRIC KEY SSN_Key_LUONG DECRYPTION BY CERTIFICATE LUONG WITH PASSWORD = '1412503';
	SELECT MANV, HOTEN, EMAIL, CONVERT(INT, DECRYPTBYKEY(LUONG)) as LUONGCB FROM NHANVIEN
END

--EXEC SP_INS_NHANVIEN 'NV001', N'Trần Thanh Ngọc', 'thanhngoc@gmail.com', 3000000, 'NV001', 'ngoc123'
--EXEC SP_INS_NHANVIEN 'NV002', N'Trần Thanh', 'thanh@gmail.com', 4000000, 'NV002', 'thanh123'
--EXEC SP_INS_NHANVIEN 'NV003', N'Trần Thanh', 'thanh@gmail.com', 4000000, 'NV003', 'nv3123'

--EXEC SP_SEL_NHANVIEN 
------------------------------------------------------------